name: CI

on:

  push:

    branches: [ main ]

  pull_request:

    branches: [ main ]


jobs:
  build:

    name: Running tests
    runs-on: macos-latest 

    strategy:
      matrix:
        node-version: [17.x]


    env:
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      NODE_ENV: ${{ secrets.NODE_ENV }}
      PORT: ${{ secrets.PORT }}
      TEST_DB: ${{ secrets.TEST_DB }}
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    - name: Install
      run: npm install -f
    - name: Test
      run: npm test
